# Generated by Django 3.1.6 on 2021-06-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('born', models.DateField(blank=True, null=True, verbose_name='Born')),
                ('heroes', models.ManyToManyField(blank=True, null=True, to='heroes.Hero', verbose_name='Heroes')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
