# Generated by Django 3.1.6 on 2021-06-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='heroes',
            field=models.ManyToManyField(blank=True, to='heroes.Hero', verbose_name='Heroes'),
        ),
    ]
